[package]
name = "configopt-derive"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.0"
proc-macro2 = "1.0.8"
proc_macro_roids = "0.7.0"
quote = "1.0.2"
syn = "1.0.14"
