[package]
name = "configopt"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
edition = "2018"

[dependencies]
colosseum = "0.2.2"
configopt-derive = { path = "../configopt-derive", version = "=0.1.0" }
lazy_static = "1.4.0"
structopt = "0.3.7"
url = "2.0.0" # Used only to implment traits on `Url`

[dev-dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
